---

- name: Remove deprecated repo filename.
  file:
    path: /etc/apt/sources.list.d/jitsi_stable.list
    state: absent

- name: Remove deprecated repo filename.
  file:
    path: /etc/apt/sources.list.d/jitsi_unstable.list
    state: absent


- name: Determine repo strategy.
  set_fact:
    jitsi_strategy: "{{ 'unstable' if jitsi_version == 'nightly' else 'stable' }}"

# Both stable and unstable repos use the same signing key.
- name: Configure signing key for Jitsi repository.
  apt_key:
    id: 66A9CD0595D6AFA247290D3BEF8B479E2DC1389C
    url: "https://download.jitsi.org/jitsi-key.gpg.key"
    state: present

- name: Install Jitsi apt repo.
  apt_repository:
    repo: "{{ item.value.repo_url }}"
    state: "{{ 'present' if jitsi_strategy == item.key else 'absent' }}"
    # Ansible will automatically add the ".list" suffix.
    filename: /etc/apt/sources.list.d/jitsi_meet
  with_dict: "{{ jitsi_meet_apt_repos }}"



- name: Set debconf options for jitsi-meet.
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ jitsi_meet_debconf_settings }}"
  when: not videobridge_only
  notify:
    - restart jitsi-videobridge
    - restart jicofo
    - restart prosody

- name: Install base jitsi packages.
  apt:
    name: "{{ jitsi_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: jitsi_version != 'shib' and not videobridge_only

#
#- name: Install Jitsi Meet (full package)
#  apt:
#    name: jitsi-meet
#    state: latest
#    update_cache: yes
#    cache_valid_time: 3600
#  when: jitsi_version != 'shib' and not videobridge_only

- name: Install Jitsi Videobridge
  apt:
    name: jitsi-videobridge2
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: videobridge_only

- name: Install Aug 19 version of Jitsi)
  apt:
    deb: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ jitsi_1908_packages }}"
  when: jitsi_version == 'shib' and not videobridge_only

