---
- include_tasks: install.yml
- include_tasks: install.yml # Hack: One needs to install it twice!

- name: Backup old jibri.jar file
  copy:
    src: /opt/jitsi/jibri/jibri.jar
    dest: /opt/jitsi/jibri/jibri-backup.jar
    remote_src: true

- name: Copy local .jar file
  copy: 
    src: jibri-8.0-SNAPSHOT-jar-with-dependencies.jar
    dest: /opt/jitsi/jibri/jibri.jar
    mode: '0644'
    owner: root
    group: root
  notify: Restart jibri

- name: Remove java-11
  apt:
    name: openjdk-11-jre-headless
    state: absent

- name: Install java-8
  apt:
    name: "{{item}}"
    state: present
  loop: 
    - openjdk-8-jdk
    - openjdk-8-jdk-headless
    - openjdk-8-jre
    - openjdk-8-jre-headless

- name: Add config of jibri
  template:
    src: config.json.j2
    dest: /etc/jitsi/jibri/config.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart jibri

- name: Install upload packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - s3cmd
    - jq

- name: Add S3 config file
  template:
    src: s3cmd.cfg
    dest: "{{ jibri_recording_S3_config_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Add upload_streamfile.sh
  template:
    src: upload_streamfile.sh.j2
    dest: "{{ jibri_recording_S3_custom_script_path }}"
    owner: root
    group: root
    mode: '0755'

- name: Add cronjob file
  template:
    src: remove_old_recordings.sh.j2
    dest: "/usr/local/bin/remove_old_recordings.sh"
    mode: '0755'
    owner: root
    group: root

- name: Add cronjobs
  cron:
    name: "Delete old recordings {{ item }}"
    hour: "1"
    minute: "5"
    job: "/usr/local/bin/remove_old_recordings.sh {{ item }} > /dev/null 2>&1"
  loop:
    - '/srv/recordings'

- name: Enable jibri service
  service:
    name: jibri
    state: started
    enabled: yes
